apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replicaset
  labels:
    app: nginx-replicaset
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      tier: nginx-pod
  template:
    metadata:
      labels:
        tier: nginx-pod
    spec:
      containers:
      - name: nginx-app
        image: nginx